### ISSUE TITLE
Google News keeps repeating

### ISSUE THREAD

**Issue by williamscody** [mdp/morse.mdp.im#21]
Over the last few days, it appears that your news source has begun using Google News.  Unfortunately, "Google News" is repeatedly transcribed to Morse, sometimes 3 or 4 times in a row.  

I understand that Google probably requires the citation as the news source, but one time for each headline should be adequate.   Perhaps a filter could be added to avoid this issue.

Otherwise, I find this a daily essential resource to improve my copying skills.  Thank you for this fine service.

**Comment by mdp** [comment]
Hey William, thanks for bringing this to my attention. I didn't know this was happening, but it looks like the headlines API I use is no longer returning titles for Google New items. Now the title returned is just "Google News" which is why it's all over the place. I've updated it to just the BBC but it means they'll be less headlines (10 vs 20) for the time being until I can find a better headline source.

Unfortunately a lot of the other headlines sources (Reuters etc), use uninformative headlines like "State of the Union: Where to watch" and then a really long description, which doesn't really work for this type of application. I'll play around with the API more later this week and see if I can find a better solution / source
